FROM jenkins/jenkins:lts-alpine

ENV JAVA_OPTS="-Djenkins.install.runSetupWizard=false"

COPY security.groovy /usr/share/jenkins/ref/init.groovy.d/security.groovy

COPY plugins.txt /usr/share/jenkins/ref/plugins.txt

COPY --from=docker/compose:latest /usr/local/bin/docker-compose /usr/bin/docker-compose

COPY --from=library/docker:latest /usr/local/bin/docker /usr/bin/docker

RUN /usr/local/bin/install-plugins.sh < /usr/share/jenkins/ref/plugins.txt